# Preparation

## Modules

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.math as tfm
import datetime

from pandas import DataFrame
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SimpleRNN, GRU, Bidirectional, Dropout
from tensorflow.keras.callbacks import EarlyStopping

from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PowerTransformer

2022-06-04 17:14:21.330024: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

## Data preparation

In [2]:
def label(df, t=60):
#     df = df[df.shape[0] % t:]
    df2 = df.groupby(np.arange(len(df))//t, axis=0).agg({'Timestamp': 'min', 'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last',
                                'N/A': 'sum', 'Timestamp End': 'max', 'N/A.1': 'sum', 'N/A.2': 'sum', 'N/A.3': 'sum',
                                'N/A.4': 'sum', 'N/A.5': 'sum', 'Time_UTC_Start': 'first'})
    df2.rename(columns = {'N/A': 'Volumn', 'N/A.1': 'Quote_asset_volume', 'N/A.2': 'Number_of_trades',
                         'N/A.3': 'Taker_buy_base_asset_volume', 'N/A.4': 'Taker_buy_quote_asset_volume'}, inplace = True)
    length = df2.shape[0]
    op = df2['Open'].values.reshape(length,1)
    cl = df2['Close'].values.reshape(length,1 )
    v = np.ones((length, 1)) * (op < cl)
    df2['label'] = v
    df2.index = df2["Timestamp"]
    df2.drop(columns=["Timestamp", "N/A.5"], inplace=True)
    return df2

In [3]:
from Feature import Feature


# Dataframe with 15 minutes between each row
a = pd.read_csv("../binance-BTCUSDT-1m.csv")
a = a[a["Timestamp"] >= 1531972800000]
df_1h = label(a)
df = df_1h
# We train the model with a half of df_15min
# df = df_1h.iloc[int(len(df_1h)*0.6):, :]
df

,Open,High,Low,Close,Volumn,Timestamp End,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,Time_UTC_Start,label
Timestamp,,,,,,,,,,,,
1531972800000,7316.00,7346.60,7311.00,7315.02,1055.480420,1531976399999,7.732585e+06,6389,564.139680,4.133182e+06,2018-07-19 04:00:00,0.0
1531976400000,7315.03,7343.85,7306.00,7330.74,1136.350469,1531979999999,8.321112e+06,6431,656.729180,4.809039e+06,2018-07-19 05:00:00,1.0
1531980000000,7334.58,7366.16,7329.50,7343.66,1442.348007,1531983599999,1.060020e+07,9190,868.183922,6.380686e+06,2018-07-19 06:00:00,1.0
1531983600000,7340.65,7349.94,7308.23,7316.66,1569.899510,1531987199999,1.151443e+07,7196,1003.016457,7.357515e+06,2018-07-19 07:00:00,0.0
1531987200000,7316.67,7339.45,7291.37,7326.61,1230.398072,1531990799999,9.010480e+06,7446,664.377959,4.866483e+06,2018-07-19 08:00:00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1651892400000,35953.63,35959.99,35760.00,35812.21,950.370320,1651895999999,3.407918e+07,23893,440.466220,1.579364e+07,2022-05-07 03:00:00,0.0
1651896000000,35812.22,35882.67,35725.72,35746.63,1038.354640,1651899599999,3.717972e+07,25448,505.470370,1.809844e+07,2022-05-07 04:00:00,0.0
1651899600000,35746.62,35900.00,35722.24,35898.95,897.235930,1651903199999,3.215497e+07,22906,428.196080,1.534393e+07,2022-05-07 05:00:00,1.0
1651903200000,35898.96,35909.75,35790.02,35806.27,890.855280,1651906799999,3.193104e+07,23642,411.973150,1.476535e+07,2022-05-07 06:00:00,0.0
1651906800000,35806.28,35956.51,35800.00,35951.69,1388.490910,1651910039999,4.978675e+07,23475,646.898060,2.320556e+07,2022-05-07 07:00:00,1.0

In [9]:
a = Feature(df.copy())
for i in [4,8,12,16,24,48,72]:
    a.price_EMA(days=i, inplace=True)
    a.price_SMA(days=i, inplace=True)
    a.price_WMA(days=i, inplace=True)
    a.volumn_EMA(days=i, inplace=True)
    a.volumn_SMA(days=i, inplace=True)
    a.volumn_WMA(days=i, inplace=True)
    a.RS(days=i, inplace=True)
    a.RSI(days=i, inplace=True)
    a.std(days=i, inplace=True)
    a.raw_money_flow(inplace=True)
    a.price_up(inplace=True)
    a.price_down(inplace=True)
    a.price_up_SMA(days=i, inplace=True)
    a.price_down_SMA(days=i, inplace=True)
    a.plus_DM(inplace=True)
    a.minus_DM(inplace=True)
    a.price_diff(inplace=True)
    a.smoothed_plus_DM(days=i, inplace=True)
    a.smoothed_minus_DM(days=i, inplace=True)
    a.TR(inplace=True)
    a.std(days=i, inplace=True)
    a.mad(days=i, inplace=True)
    a.ATR(days=i, inplace=True)
    a.CCI(days=i, inplace=True)
    a.DX(days=i, inplace=True)
    a.ADX(days=i, inplace=True)
    a.PPO(inplace=True)
    a.BOP(days=i, inplace=True)
    a.MFI(days=i, inplace=True)
    a.MACD()
a.dropna(inplace=True)

/home/hoangvictor/Documents/Data Science/Machine Learning/Class/Project/Bitcoin_Price_Prediction/indicators/VolumnPriceIndicator.py:53: RuntimeWarning: divide by zero encountered in double_scalars
  lst[i] = 100 - 100/(1+(up/down))
/home/hoangvictor/Documents/Data Science/Machine Learning/Class/Project/Bitcoin_Price_Prediction/indicators/VolumnPriceIndicator.py:53: RuntimeWarning: divide by zero encountered in double_scalars
  lst[i] = 100 - 100/(1+(up/down))
/home/hoangvictor/Documents/Data Science/Machine Learning/Class/Project/Bitcoin_Price_Prediction/indicators/VolumnPriceIndicator.py:53: RuntimeWarning: divide by zero encountered in double_scalars
  lst[i] = 100 - 100/(1+(up/down))
/home/hoangvictor/Documents/Data Science/Machine Learning/Class/Project/Bitcoin_Price_Prediction/indicators/VolumnPriceIndicator.py:53: RuntimeWarning: divide by zero encountered in double_scalars
  lst[i] = 100 - 100/(1+(up/down))

In [10]:
a.to_csv("data_with_features_ver1.csv")

In [12]:
len(a.columns)

176

In [ ]:
import pandas as pd
pd.read_csv("data_with_features_ver1.csv")