# Preparation

## Modules

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.math as tfm
import datetime

from pandas import DataFrame
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SimpleRNN, GRU, Bidirectional, Dropout
from tensorflow.keras.callbacks import EarlyStopping

from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PowerTransformer

## Data preparation

In [2]:
from Feature import Feature
from utils.label import label


# Dataframe with 15 minutes between each row
df_15min = label("../binance-BTCUSDT-1m.csv")


# We train the model with a half of df_15min
df = df_15min.iloc[int(len(df_15min)*0.6):, :]

In [3]:
a = Feature(df.copy())

# a.price_EMA(days=5, inplace=True)
# a.price_SMA(days=5, inplace=True)
# a.price_WMA(days=5, inplace=True)
# a.volumn_EMA(days=5, inplace=True)
# a.volumn_SMA(days=5, inplace=True)
# a.volumn_WMA(days=5, inplace=True)
# a.RS(days=5, inplace=True)
# a.RSI(days=5, inplace=True)
# a.std(days=5, inplace=True)
# a.raw_money_flow(inplace=True)
# a.price_up(inplace=True)
# a.price_down(inplace=True)
# a.price_up_SMA(days=5,inplace=True)
# a.price_down_SMA(days=5, inplace=True)
a.plus_DM(inplace=True)
a.minus_DM(inplace=True)
a.smoothed_plus_DM(inplace=True)
a.smoothed_minus_DM(inplace=True)
a.TR(inplace=True)
a.ATR(inplace=True)
a.DX(inplace=True)
a.ADX(inplace=True)
# a.dropna(inplace=True)

,Open,High,Low,Close,Volumn,Timestamp End,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,...,plus_DM,minus_DM,smoothed_plus_DM14,smoothed_minus_DM14,TR,ATR14,plus_DI14,minus_DI14,DX14,ADX14
Timestamp,,,,,,,,,,,,,,,,,,,,,
1603909440000,13173.22,13240.00,13169.31,13200.87,726.910294,1603910339999,9.605562e+06,10880,346.493208,4.578025e+06,...,0.00,0.00,NaN,NaN,70.69,NaN,NaN,NaN,NaN,<NA>
1603910340000,13200.87,13207.92,13172.27,13175.66,537.956055,1603911239999,7.095975e+06,8703,230.116581,3.035192e+06,...,0.00,0.00,NaN,NaN,35.65,NaN,NaN,NaN,NaN,<NA>
1603911240000,13175.67,13230.00,13155.96,13201.46,760.103612,1603912139999,1.003671e+07,11083,332.470930,4.389568e+06,...,22.08,16.31,NaN,NaN,74.04,NaN,NaN,NaN,NaN,<NA>
1603912140000,13201.46,13229.62,13174.16,13225.91,805.254947,1603913039999,1.062218e+07,11728,340.234623,4.488559e+06,...,0.00,0.00,NaN,NaN,55.46,NaN,NaN,NaN,NaN,<NA>
1603913040000,13225.91,13255.00,13200.00,13205.59,914.407839,1603913939999,1.210203e+07,11677,456.067941,6.037120e+06,...,25.38,0.00,NaN,NaN,55.00,NaN,NaN,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651905540000,35858.19,35878.00,35795.54,35795.55,231.841700,1651906439999,8.311628e+06,5817,86.377500,3.096591e+06,...,11.85,0.00,156.001429,317.571429,82.46,86.096429,181.193844,368.855519,34.117242,46.654056
1651906440000,35795.54,35832.12,35790.02,35812.80,154.689420,1651907339999,5.539456e+06,5981,91.672010,3.282832e+06,...,0.00,5.52,144.151429,191.447857,42.10,77.674286,185.584492,246.475208,14.093126,43.274766
1651907340000,35812.81,35870.00,35800.00,35867.66,613.847520,1651908239999,2.198320e+07,7098,179.258800,6.422060e+06,...,37.88,0.00,217.205714,185.927857,70.00,77.490714,280.299022,239.935660,7.758683,32.686948
1651908240000,35867.65,35912.00,35826.36,35902.74,330.432300,1651909139999,1.185255e+07,5798,194.712580,6.983194e+06,...,42.00,0.00,260.325714,159.955714,85.64,76.810714,338.918492,208.246617,23.881617,13.640665
1651909140000,35902.75,35956.51,35880.47,35951.69,368.392130,1651910039999,1.323538e+07,7430,228.147900,8.196411e+06,...,44.51,0.00,304.166429,123.537143,76.04,77.051429,394.757676,160.330762,42.232354,8.910321

In [4]:
a[["ADX14", "DX14","ATR14","smoothed_minus_DM14", "smoothed_plus_DM14"]].head(40)

,ADX14,DX14,ATR14,smoothed_minus_DM14,smoothed_plus_DM14
Timestamp,,,,,
1603909440000,<NA>,NaN,NaN,NaN,NaN
1603910340000,<NA>,NaN,NaN,NaN,NaN
1603911240000,<NA>,NaN,NaN,NaN,NaN
1603912140000,<NA>,NaN,NaN,NaN,NaN
1603913040000,<NA>,NaN,NaN,NaN,NaN
1603913940000,<NA>,NaN,NaN,NaN,NaN
1603914840000,<NA>,NaN,NaN,NaN,NaN
1603915740000,<NA>,NaN,NaN,NaN,NaN
1603916640000,<NA>,NaN,NaN,NaN,NaN
1603917540000,<NA>,NaN,NaN,NaN,NaN
1603918440000,<NA>,NaN,NaN,NaN,NaN
1603919340000,<NA>,NaN,NaN,NaN,NaN
1603920240000,<NA>,NaN,NaN,NaN,NaN
1603921140000,<NA>,9.496214,52.882857,142.990714,118.188571
1603922040000,<NA>,4.267592,50.311429,142.990714,131.285714
1603922940000,<NA>,7.891819,50.578571,142.990714,167.493571
1603923840000,<NA>,18.548301,49.485000,127.845714,186.072143
1603924740000,<NA>,8.654835,48.186429,127.845714,152.072143
1603925640000,<NA>,3.004637,46.336429,136.466429,128.505000
1603926540000,<NA>,27.834556,45.265000,91.139286,161.445000
1603927440000,<NA>,40.170253,44.010714,81.277857,190.419286
1603928340000,<NA>,5.591636,45.540714,129.897143,145.284286
1603929240000,<NA>,11.899608,44.905714,106.686429,135.506429
1603930140000,<NA>,32.779330,44.330714,89.124286,176.045000
1603931040000,<NA>,5.341930,43.737857,127.620714,142.025000
1603931940000,<NA>,1.824906,44.277857,147.305000,142.025000
1603932840000,<NA>,34.343434,40.132857,69.410714,142.025000
1603933740000,<NA>,29.514380,37.787857,69.410714,127.539286
1603934640000,16.547658,30.499370,40.649286,213.532857,113.722143
1603935540000,18.421357,18.415191,43.373571,138.802857,201.463571
1603936440000,29.636215,10.844982,42.313571,138.802857,111.642143
1603937340000,17.874462,29.413013,43.150714,204.682857,111.642143
1603938240000,12.17127,21.227012,43.930000,171.810714,111.642143
1603939140000,28.828299,20.587681,43.818571,168.990714,111.287857
1603940040000,21.181345,48.008932,45.840714,230.801429,81.073571
1603940940000,22.546341,47.253294,45.448571,226.333571,81.073571
1603941840000,47.954958,21.022604,45.782857,197.200714,128.690000
1603942740000,45.379673,16.482010,47.002857,197.200714,141.393571
1603943640000,20.698276,8.392493,46.475000,178.638571,150.975714
1603944540000,15.904187,7.855248,47.182857,173.375000,148.120714

In [10]:
a = Feature(df.copy())
a.BOP(days=3,inplace=True)
a[["Close", "Open", "Low", "High","BOP3"]].head(20)

                  Close      Open       Low      High      BOP3
Timestamp
1603909440000  13200.87  13173.22  13169.31  13240.00       NaN
1603910340000  13175.66  13200.87  13172.27  13207.92       NaN
1603911240000  13201.46  13175.67  13155.96  13230.00       NaN
1603912140000  13225.91  13201.46  13174.16  13229.62  0.010772
1603913040000  13205.59  13225.91  13200.00  13255.00  0.027344
1603913940000  13168.49  13205.38  13156.00  13209.09  0.139910
1603914840000  13190.01  13168.50  13145.38  13191.58 -0.207818
1603915740000  13200.65  13190.00  13183.06  13214.47 -0.199576
1603916640000  13179.19  13200.76  13179.19  13225.00  0.036597
1603917540000  13197.68  13179.20  13163.40  13200.00  0.111264
1603918440000  13163.34  13197.68  13163.34  13214.00  0.124375
1603919340000  13192.40  13163.56  13160.00  13194.48 -0.214597
1603920240000  13165.77  13192.39  13100.00  13193.03  0.221164
1603921140000  13207.75  13165.77  13150.39  13208.63 -0.042523
1603922040000  13211.22  13207.75  13188.82  13223.51  0.423698
1603922940000  13226.95  13211.22  13210.61  13250.00  0.178232
1603923840000  13261.15  13226.94  13225.27  13284.00  0.406726
1603924740000  13251.97  13261.14  13241.76  13279.04  0.360622
1603925640000  13264.11  13251.97  13237.29  13266.39  0.245287
1603926540000  13280.42  13264.08  13245.38  13283.47  0.251234

In [11]:
(a["Close"] - a["Open"])/(a["High"] - a["Low"])

Timestamp
1603909440000    0.391144
1603910340000   -0.707153
1603911240000    0.348325
1603912140000    0.440858
1603913040000   -0.369455
                   ...
1651905540000   -0.759641
1651906440000    0.409976
1651907340000    0.783571
1651908240000    0.409738
1651909140000    0.643609
Length: 53334, dtype: float64

In [9]:
(a[["Close"]] - a[["Open"]])

               Close  Open
Timestamp
1603909440000    NaN   NaN
1603910340000    NaN   NaN
1603911240000    NaN   NaN
1603912140000    NaN   NaN
1603913040000    NaN   NaN
...              ...   ...
1651905540000    NaN   NaN
1651906440000    NaN   NaN
1651907340000    NaN   NaN
1651908240000    NaN   NaN
1651909140000    NaN   NaN

[53334 rows x 2 columns]

In [3]:
a = Feature(df.copy())
a.CCI(days=3,inplace=True)
a.mad(days=3,inplace=True)
a.typical_price(inplace=True)
print(a.columns)
print(a[["mad3", "CCI3", "typical_price"]].head(8))

Index(['Open', 'High', 'Low', 'Close', 'Volumn', 'Timestamp End',
       'Quote_asset_volume', 'Number_of_trades', 'Taker_buy_base_asset_volume',
       'Taker_buy_quote_asset_volume', 'Time_UTC_Start', 'label',
       'typical_price', 'CCI3', 'mad3'],
      dtype='object')
                    mad3       CCI3  typical_price
Timestamp
1603909440000        NaN        NaN   13203.393333
1603910340000        NaN        NaN   13185.283333
1603911240000        NaN        NaN   13195.806667
1603912140000        NaN        NaN   13209.896667
1603913040000  13.031111  59.157572   13220.196667
1603913940000  20.601111 -80.225806   13177.860000
1603914840000  12.961111 -80.142878   13175.656667
1603915740000  15.917778  63.199777   13199.393333

In [4]:
(13203.393333 + 13185.283333 + 13195.806667) / 3

13194.827777666665

In [6]:
abs(a["typical_price"][0:3] - a["typical_price"][0:3].mean()).sum()/3

6.3629629629625315

In [7]:
abs(a["typical_price"][1:4] - a["typical_price"][1:4].mean()).sum()/3

8.600740740740852

In [8]:
abs(a["typical_price"][2:5] - a["typical_price"][2:5].mean()).sum()/3

8.551111111111823